#!/usr/bin/env python3

"""Generate root .env file for docker-compose deployment."""

from __future__ import annotations

import argparse
import secrets
import string
import sys
from datetime import datetime, timezone
from pathlib import Path


def generate_password(length: int = 32) -> str:
    alphabet = string.ascii_letters + string.digits + "-_"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def build_env_text(args: argparse.Namespace) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    postgres_password = generate_password()
    jwt_secret = secrets.token_urlsafe(64)

    lines = [
        "# Auto-generated by scripts/generate_compose_env.py",
        f"# Generated at {timestamp}",
        "",
        f"TRAEFIK_ACME_EMAIL={args.acme_email}",
        f"TRAEFIK_WEB_HOST={args.web_host}",
        f"TRAEFIK_API_HOST={args.api_host}",
        "",
        f"POSTGRES_USER={args.postgres_user}",
        f"POSTGRES_DB={args.postgres_db}",
        f"POSTGRES_PASSWORD={postgres_password}",
        "",
        f"JWT_SECRET={jwt_secret}",
        "",
    ]
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate deployment .env file for docker-compose."
    )
    parser.add_argument(
        "--output",
        default=".env",
        help="Path to output env file (default: .env)",
    )
    parser.add_argument(
        "--acme-email",
        required=True,
        help="Email for Let's Encrypt ACME registration",
    )
    parser.add_argument(
        "--web-host",
        default="home.vyachik-dev.ru",
        help="Public web host used by Traefik router",
    )
    parser.add_argument(
        "--api-host",
        default="home-server.vyachik-dev.ru",
        help="Public API host used by Traefik router",
    )
    parser.add_argument(
        "--postgres-user",
        default="postgres",
        help="Postgres user for the app",
    )
    parser.add_argument(
        "--postgres-db",
        default="task_tracker",
        help="Postgres database name for the app",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing output file",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_path = Path(args.output)

    if output_path.exists() and not args.force:
        print(
            f"Refusing to overwrite existing file: {output_path}\n"
            "Use --force to overwrite.",
            file=sys.stderr,
        )
        return 1

    output_path.write_text(build_env_text(args), encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
